services:
  mongo:
    image: mongo:7
    container_name: tec_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: tec_backend
    ports:
      - "3001:3001"
    env_file:
      - ./infra/.env
    environment:
      # IMPORTANTE: dentro de docker NO uses localhost para mongo
      - MONGO_URI=mongodb://mongo:27017/tec_environmental_risk
      - PORT=3001
    depends_on:
      - mongo
    volumes:
      # opcional para dev hot-reload (si tu Dockerfile soporta dev)
      - ./backend:/app
      - /app/node_modules

volumes:
  mongo_data:
